version: "3"

services:
  db:
    container_name: mariadb_selfcheckout
    image: mariadb
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
